"""created author and book tables

Revision ID: 221fa1e3dc72
Revises: c0ad95ca11c4
Create Date: 2023-09-27 22:25:15.997568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '221fa1e3dc72'
down_revision = 'c0ad95ca11c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'authors', ['author_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('author_id')

    # ### end Alembic commands ###
